"""Plan and plan-step models (Фаза 2 §1 — Planning Mode).

A ``Plan`` is a structured decomposition of a complex task into ordered steps
with dependency edges (DAG). Plans are generated by the LLM, reviewed/edited
by the user, approved, and then executed step-by-step within the agent loop.

``PlanStep`` is a single actionable item within a plan: its position in the
sequence, a human-readable title/description, dependency references (by
position), suggested tools, and execution status.

``PlanTemplate`` stores reusable plan skeletons for common task patterns
(research, code review, documentation, etc.).
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import Column, Text
from sqlalchemy.types import JSON
from sqlmodel import Field

from app.models.base import TimestampMixin

# Plan status values.
PLAN_STATUS_DRAFT = "draft"
PLAN_STATUS_APPROVED = "approved"
PLAN_STATUS_EXECUTING = "executing"
PLAN_STATUS_COMPLETED = "completed"
PLAN_STATUS_FAILED = "failed"
PLAN_STATUS_CANCELLED = "cancelled"

PLAN_STATUSES = frozenset(
    {
        PLAN_STATUS_DRAFT,
        PLAN_STATUS_APPROVED,
        PLAN_STATUS_EXECUTING,
        PLAN_STATUS_COMPLETED,
        PLAN_STATUS_FAILED,
        PLAN_STATUS_CANCELLED,
    }
)

# Plan step status values.
STEP_STATUS_PENDING = "pending"
STEP_STATUS_RUNNING = "running"
STEP_STATUS_COMPLETED = "completed"
STEP_STATUS_FAILED = "failed"
STEP_STATUS_SKIPPED = "skipped"

STEP_STATUSES = frozenset(
    {
        STEP_STATUS_PENDING,
        STEP_STATUS_RUNNING,
        STEP_STATUS_COMPLETED,
        STEP_STATUS_FAILED,
        STEP_STATUS_SKIPPED,
    }
)


class Plan(TimestampMixin, table=True):
    """A structured task plan generated by the LLM and approved by the user."""

    __tablename__ = "plans"

    id: int | None = Field(default=None, primary_key=True)
    conversation_id: int = Field(foreign_key="conversations.id", index=True)
    run_id: int | None = Field(default=None, foreign_key="agent_runs.id", index=True)
    title: str | None = None
    # See PLAN_STATUSES above.
    status: str = Field(default=PLAN_STATUS_DRAFT, index=True)
    # Denormalized step list (JSON array of step dicts) for quick reads.
    steps: list[dict[str, Any]] | None = Field(default=None, sa_column=Column("steps", JSON))
    # Arbitrary metadata (e.g. source template id, generation params).
    metadata_: dict[str, Any] | None = Field(default=None, sa_column=Column("metadata_", JSON))


class PlanStep(TimestampMixin, table=True):
    """A single step within a plan."""

    __tablename__ = "plan_steps"

    id: int | None = Field(default=None, primary_key=True)
    plan_id: int = Field(foreign_key="plans.id", index=True)
    # Ordering within the plan (0-based).
    position: int
    title: str
    description: str | None = Field(default=None, sa_column=Column(Text))
    # See STEP_STATUSES above.
    status: str = Field(default=STEP_STATUS_PENDING)
    # Positions of steps this step depends on (DAG edges).
    depends_on: list[int] | None = Field(default=None, sa_column=Column("depends_on", JSON))
    # Suggested tool names for this step.
    tools: list[str] | None = Field(default=None, sa_column=Column("tools", JSON))
    # Brief summary of the step's execution result.
    result_summary: str | None = Field(default=None, sa_column=Column(Text))
    # The sub-run that executed this step (links to agent_runs.id).
    run_id: int | None = None


class PlanTemplate(TimestampMixin, table=True):
    """A reusable plan skeleton for common task patterns."""

    __tablename__ = "plan_templates"

    id: int | None = Field(default=None, primary_key=True)
    name: str
    description: str | None = Field(default=None, sa_column=Column(Text))
    # Template step definitions (JSON array of step dicts without runtime state).
    steps: list[dict[str, Any]] = Field(default_factory=list, sa_column=Column("steps", JSON))
    # Built-in templates ship with the app and cannot be deleted.
    is_builtin: bool = False
