[package]
name = "cool-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "cool"
path = "src/main.rs"

[dependencies]
cool-app-server = { path = "../cool-app-server" }
cool-state = { path = "../cool-state" }
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
