[package]
name = "cool-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "cool"
path = "src/main.rs"

[dependencies]
cool-acp = { path = "../cool-acp", version = "0.2.1" }
cool-agent = { path = "../cool-agent", version = "0.2.1" }
cool-app-server = { path = "../cool-app-server", version = "0.2.1" }
cool-extensions = { path = "../cool-extensions", version = "0.2.1" }
cool-http = { path = "../cool-http", version = "0.2.1" }
cool-protocol = { path = "../cool-protocol", version = "0.2.1" }
cool-security = { path = "../cool-security", version = "0.2.1" }
cool-state = { path = "../cool-state", version = "0.2.1" }
cool-store = { path = "../cool-store", version = "0.2.1" }
cool-tui = { path = "../cool-tui", version = "0.2.1" }
async-trait.workspace = true
futures-util.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json = { workspace = true }
sha2.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true

[lints]
workspace = true
