//! Memory retrieval / lifecycle parity against the real Python retrieval output.
//!
//! `tests/fixtures/memory_parity.json` was generated by
//! `backend/app/memory/retrieval.py` + `lifecycle.py` against the baseline
//! schema with a frozen clock (`2026-06-15 12:00:00 UTC`). It embeds the exact
//! seed SQL so the Rust test seeds byte-identical rows, then asserts the
//! ordered ids, composite scores and raw FTS ranks match exactly.

mod common;

use common::{create_python_database, temp_database};
use cool_store::memory::{
    MemoryQuery, apply_decay, expire_items, search_at, vector_index_available, vector_search,
};
use cool_store::{LegacyStore, StoreOptions};
use serde::Deserialize;
use tempfile::TempDir;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    #[allow(dead_code)]
    now: String,
    now_micros: i64,
    seed_sql_retrieval: String,
    seed_sql_lifecycle: String,
    scenarios: Vec<Scenario>,
    lifecycle: Lifecycle,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Scenario {
    name: String,
    query: MemoryQuery,
    ids: Vec<i64>,
    scores: Vec<f64>,
    fts_ranks: Vec<Option<f64>>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Lifecycle {
    decay: u64,
    ttl: u64,
    validity: u64,
    pending: u64,
    expire_total: u64,
}

fn fixture() -> Fixture {
    serde_json::from_str(include_str!("fixtures/memory_parity.json")).expect("fixture json")
}

/// The rerank arithmetic is replicated exactly (same operation order, IEEE
/// f64), but the *input* BM25 rank is produced by SQLite's FTS5 implementation
/// and the Python environment and rusqlite's bundled SQLite can differ by 1
/// ULP. A small relative tolerance absorbs that while still catching any real
/// divergence in the formula.
const TOLERANCE: f64 = 1e-9;

fn approx(left: f64, right: f64) -> bool {
    (left - right).abs() <= TOLERANCE * (1.0 + right.abs())
}

fn store_with(seed: &str) -> (TempDir, LegacyStore) {
    let directory = TempDir::new().expect("tempdir");
    let path = temp_database(directory.path(), "harness.db");
    create_python_database(&path, seed);
    let store = LegacyStore::open(
        &path,
        &StoreOptions {
            initialize_if_missing: false,
            ..StoreOptions::default()
        },
    )
    .expect("adopt");
    (directory, store)
}

#[test]
fn retrieval_matches_python_ordering_scores_and_fts_ranks() {
    let fixture = fixture();
    let (_directory, store) = store_with(&fixture.seed_sql_retrieval);
    assert!(!fixture.scenarios.is_empty());

    for scenario in &fixture.scenarios {
        let hits = search_at(&store, "local-user", &scenario.query, fixture.now_micros)
            .unwrap_or_else(|error| panic!("scenario {}: {error}", scenario.name));

        let ids: Vec<i64> = hits.iter().map(|hit| hit.item.id).collect();
        assert_eq!(
            ids, scenario.ids,
            "ordered ids differ for {}",
            scenario.name
        );
        assert_eq!(
            hits.len(),
            scenario.scores.len(),
            "hit count differs for {}",
            scenario.name
        );

        for (hit, expected) in hits.iter().zip(&scenario.scores) {
            assert!(
                approx(hit.score, *expected),
                "score mismatch for memory {} in {}: {} vs {}",
                hit.item.id,
                scenario.name,
                hit.score,
                expected
            );
        }
        for (hit, expected) in hits.iter().zip(&scenario.fts_ranks) {
            match (hit.fts_rank, expected) {
                (None, None) => {}
                (Some(rank), Some(expected)) => assert!(
                    approx(rank, *expected),
                    "fts rank mismatch for memory {} in {}: {} vs {}",
                    hit.item.id,
                    scenario.name,
                    rank,
                    expected
                ),
                (actual, expected) => panic!(
                    "fts rank presence mismatch for memory {} in {}: {actual:?} vs {expected:?}",
                    hit.item.id, scenario.name
                ),
            }
        }
    }
}

#[test]
fn lifecycle_sweeps_match_python_counts() {
    let fixture = fixture();
    let (_directory, store) = store_with(&fixture.seed_sql_lifecycle);

    let decay = apply_decay(&store, "local-user", &fixture.now).expect("decay");
    assert_eq!(decay, fixture.lifecycle.decay, "decay sweep count");

    let expired = expire_items(&store, "local-user", &fixture.now).expect("expire");
    assert_eq!(
        expired, fixture.lifecycle.expire_total,
        "expire sweep count = ttl {} + validity {} + pending {}",
        fixture.lifecycle.ttl, fixture.lifecycle.validity, fixture.lifecycle.pending
    );
}

#[test]
fn vector_leg_degrades_when_the_vec_table_is_absent() {
    let fixture = fixture();
    let (_directory, store) = store_with(&fixture.seed_sql_retrieval);

    assert!(!vector_index_available(&store).expect("available check"));
    let hits = vector_search(&store, "local-user", &[0.0, 1.0, 2.0], 5).expect("vector search");
    assert!(
        hits.is_empty(),
        "no sqlite-vec table -> empty, never an error"
    );

    // Requesting hybrid without an embedding still degrades to FTS-only.
    let mut query = MemoryQuery {
        text: Some("rust".to_string()),
        limit: 3,
        hybrid: true,
        ..MemoryQuery::default()
    };
    let hybrid = search_at(&store, "local-user", &query, fixture.now_micros).expect("hybrid");
    query.hybrid = false;
    let fts_only = search_at(&store, "local-user", &query, fixture.now_micros).expect("fts");
    let hybrid_ids: Vec<i64> = hybrid.iter().map(|hit| hit.item.id).collect();
    let fts_ids: Vec<i64> = fts_only.iter().map(|hit| hit.item.id).collect();
    assert_eq!(hybrid_ids, fts_ids);
    assert!(hybrid.iter().all(|hit| hit.vector_score.is_none()));
}
