"""Schema conformance for ACP frames produced by the Rust ``cool acp`` adapter.

The Rust M9 adapter emits the same ACP v1 frame subset as the M4 Python adapter.
The committed fixtures are generated by ``cargo test -p cool-acp`` (blessed with
``COOL_ACP_UPDATE_GOLDEN=1``) and validated here against the pinned upstream
schema, which keeps JSON-Schema-level validation out of the Rust test binary.
"""

from __future__ import annotations

import json
from pathlib import Path

from jsonschema import Draft202012Validator

ROOT = Path(__file__).parents[2]
ACP_SCHEMA = json.loads((ROOT / "schemas" / "acp-v1.schema.json").read_text(encoding="utf-8"))
RUST_FIXTURES = (
    ROOT / "crates" / "cool-acp" / "tests" / "golden" / "acp-v1-frames.json"
)


def test_rust_acp_fixtures_are_schema_valid_and_cover_the_supported_surface() -> None:
    frames = json.loads(RUST_FIXTURES.read_text(encoding="utf-8"))
    assert frames, "the Rust adapter fixture must not be empty"

    validator = Draft202012Validator(ACP_SCHEMA)
    for frame in frames:
        errors = list(validator.iter_errors(frame))
        assert not errors, "\n".join(error.message for error in errors[:5])

    methods = {
        frame.get("method")
        for frame in frames
        if isinstance(frame.get("method"), str)
    }
    assert "session/update" in methods
    assert "session/request_permission" in methods
    updates = {
        frame["params"]["update"]["sessionUpdate"]
        for frame in frames
        if frame.get("method") == "session/update"
    }
    assert {"agent_message_chunk", "tool_call", "tool_call_update"} <= updates
    results = [frame["result"] for frame in frames if "result" in frame]
    assert any(result.get("stopReason") == "end_turn" for result in results)
    assert any("sessionId" in result for result in results)
    assert any("protocolVersion" in result for result in results)
