// Typed App Protocol SDK: one method per generated command.
//
// The types come from `src/generated/cool_protocol.ts` (regenerated by
// `cargo run -p cool-protocol --bin generate`); this client is the thin,
// hand-written transport-agnostic wrapper consumed by the Web facade in M11.
// Each method carries the exact command method literal so the frontend
// coverage test can match inventory entries against this file.

import type * as protocol from "./generated/cool_protocol.js";

/** Transport the SDK runs on (stdio JSON-RPC, local socket, or in-process). */
export interface CoolTransport {
  request(command: protocol.Command): Promise<protocol.ResponsePayload>;
}

export class CoolProtocolError extends Error {
  readonly protocol: protocol.ProtocolError;

  constructor(error: protocol.ProtocolError) {
    super(`${error.coolCode}: ${error.message}`);
    this.name = "CoolProtocolError";
    this.protocol = error;
  }
}

/** Thin typed client: one method per App Protocol command. */
export class CoolSdk {
  constructor(private readonly transport: CoolTransport) {}

  private async send<T>(command: protocol.Command): Promise<T> {
    const response = await this.transport.request(command);
    return response.value as T;
  }

  initialize(params: protocol.InitializeParams) { return this.send<protocol.InitializeResult>({ method: "initialize", params }); }
  sessionCreate(params: protocol.SessionCreateParams) { return this.send<protocol.SessionCreatedResult>({ method: "session.create", params }); }
  sessionLoad(params: protocol.SessionLoadParams) { return this.send<protocol.SessionLoadedResult>({ method: "session.load", params }); }
  sessionPrompt(params: protocol.SessionPromptParams) { return this.send<protocol.PromptAcceptedResult>({ method: "session.prompt", params }); }
  sessionList(params: protocol.SessionListParams) { return this.send<protocol.SessionListResult>({ method: "session.list", params }); }
  sessionHistory(params: protocol.SessionHistoryParams) { return this.send<protocol.SessionHistoryResult>({ method: "session.history", params }); }
  sessionFork(params: protocol.SessionForkParams) { return this.send<protocol.SessionForkedResult>({ method: "session.fork", params }); }
  sessionSteer(params: protocol.SessionSteerParams) { return this.send<protocol.SteerAcceptedResult>({ method: "session.steer", params }); }
  runCancel(params: protocol.RunCancelParams) { return this.send<protocol.RunCancelledResult>({ method: "run.cancel", params }); }
  runEvents(params: protocol.RunEventsParams) { return this.send<protocol.EventPage>({ method: "run.events", params }); }
  approvalResolve(params: protocol.ApprovalResolveParams) { return this.send<protocol.ApprovalResolvedResult>({ method: "approval.resolve", params }); }
  statusGet(params: protocol.StatusGetParams) { return this.send<protocol.StatusGetResult>({ method: "status.get", params }); }

  conversationsList(params: protocol.ConversationListParams) { return this.send<protocol.ConversationRecord[]>({ method: "conversations.list", params }); }
  conversationsCreate(params: protocol.ConversationCreateParams) { return this.send<protocol.ConversationRecord>({ method: "conversations.create", params }); }
  conversationsGet(params: protocol.LegacyIdParams) { return this.send<protocol.ConversationRecord>({ method: "conversations.get", params }); }
  conversationsUpdate(params: protocol.ConversationUpdateParams) { return this.send<protocol.ConversationRecord>({ method: "conversations.update", params }); }
  conversationsDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "conversations.delete", params }); }
  conversationsCompact(params: protocol.IdempotentIdParams) { return this.send<protocol.CompactResult>({ method: "conversations.compact", params }); }
  conversationsApprovals(params: protocol.ConversationApprovalsParams) { return this.send<protocol.ApprovalAuditRecord[]>({ method: "conversations.approvals", params }); }
  conversationsSearch(params: protocol.ConversationSearchParams) { return this.send<protocol.ConversationRecord[]>({ method: "conversations.search", params }); }
  conversationsBulk(params: protocol.ConversationBulkParams) { return this.send<protocol.AffectedResult>({ method: "conversations.bulk", params }); }
  runsList(params: protocol.RunListParams) { return this.send<protocol.AgentRunRecord[]>({ method: "runs.list", params }); }
  runsGet(params: protocol.LegacyIdParams) { return this.send<protocol.AgentRunRecord>({ method: "runs.get", params }); }
  runsEvents(params: protocol.RunEventsLegacyParams) { return this.send<protocol.RunEventRecord[]>({ method: "runs.events", params }); }
  runsCancel(params: protocol.IdempotentIdParams) { return this.send<protocol.AgentRunRecord>({ method: "runs.cancel", params }); }
  providersList(params: protocol.ProviderListParams) { return this.send<protocol.ProviderRecord[]>({ method: "providers.list", params }); }
  providersCreate(params: protocol.ProviderCreateParams) { return this.send<protocol.ProviderRecord>({ method: "providers.create", params }); }
  providersGet(params: protocol.LegacyIdParams) { return this.send<protocol.ProviderRecord>({ method: "providers.get", params }); }
  providersUpdate(params: protocol.ProviderUpdateParams) { return this.send<protocol.ProviderRecord>({ method: "providers.update", params }); }
  providersDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "providers.delete", params }); }
  providersModels(params: protocol.LegacyIdParams) { return this.send<protocol.ModelInfoRecord[]>({ method: "providers.models", params }); }
  memoryList(params: protocol.MemoryListParams) { return this.send<protocol.MemoryRecord[]>({ method: "memory.list", params }); }
  memoryGet(params: protocol.LegacyIdParams) { return this.send<protocol.MemoryRecord>({ method: "memory.get", params }); }
  memoryCreate(params: protocol.MemoryCreateParams) { return this.send<protocol.MemoryRecord>({ method: "memory.create", params }); }
  memoryUpdate(params: protocol.MemoryUpdateParams) { return this.send<protocol.MemoryRecord>({ method: "memory.update", params }); }
  memoryDelete(params: protocol.MemoryDeleteParams) { return this.send<protocol.LegacyOkResult>({ method: "memory.delete", params }); }
  memoryPending(params: protocol.MemoryPendingParams) { return this.send<protocol.MemoryRecord[]>({ method: "memory.pending", params }); }
  memoryConfirm(params: protocol.IdempotentIdParams) { return this.send<protocol.MemoryRecord>({ method: "memory.confirm", params }); }
  memoryReject(params: protocol.IdempotentIdParams) { return this.send<protocol.LegacyOkResult>({ method: "memory.reject", params }); }
  memoryPin(params: protocol.MemoryPinParams) { return this.send<protocol.MemoryRecord>({ method: "memory.pin", params }); }
  memoryExplain(params: protocol.LegacyIdParams) { return this.send<protocol.MemoryExplainRecord>({ method: "memory.explain", params }); }
  memoryEpisodes(params: protocol.MemoryEpisodesParams) { return this.send<protocol.EpisodeRecord[]>({ method: "memory.episodes", params }); }
  memoryStats(params: protocol.EmptyParams) { return this.send<protocol.MemoryStatsRecord>({ method: "memory.stats", params }); }
  entitiesList(params: protocol.EntityListParams) { return this.send<protocol.EntityRecord[]>({ method: "entities.list", params }); }
  entitiesGet(params: protocol.LegacyIdParams) { return this.send<protocol.EntityRecord>({ method: "entities.get", params }); }
  entitiesCreate(params: protocol.EntityCreateParams) { return this.send<protocol.EntityRecord>({ method: "entities.create", params }); }
  entitiesUpdate(params: protocol.EntityUpdateParams) { return this.send<protocol.EntityRecord>({ method: "entities.update", params }); }
  entitiesDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.LegacyOkResult>({ method: "entities.delete", params }); }
  plansList(params: protocol.PlanListParams) { return this.send<protocol.PlanRecord[]>({ method: "plans.list", params }); }
  plansGet(params: protocol.PlanIdParams) { return this.send<protocol.PlanRecord>({ method: "plans.get", params }); }
  plansUpdate(params: protocol.PlanUpdateParams) { return this.send<protocol.PlanRecord>({ method: "plans.update", params }); }
  plansApprove(params: protocol.PlanApproveParams) { return this.send<protocol.PlanRecord>({ method: "plans.approve", params }); }
  plansCancel(params: protocol.IdempotentPlanIdParams) { return this.send<protocol.PlanRecord>({ method: "plans.cancel", params }); }
  plansTemplatesList(params: protocol.EmptyParams) { return this.send<protocol.PlanTemplateRecord[]>({ method: "plans.templates_list", params }); }
  plansTemplatesCreate(params: protocol.PlanTemplateCreateParams) { return this.send<protocol.PlanTemplateRecord>({ method: "plans.templates_create", params }); }
  plansTemplatesDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "plans.templates_delete", params }); }
  subagentsRolesList(params: protocol.EmptyParams) { return this.send<protocol.SubagentRoleRecord[]>({ method: "subagents.roles_list", params }); }
  subagentsRolesGet(params: protocol.LegacyIdParams) { return this.send<protocol.SubagentRoleRecord>({ method: "subagents.roles_get", params }); }
  subagentsRolesCreate(params: protocol.SubagentRoleCreateParams) { return this.send<protocol.SubagentRoleRecord>({ method: "subagents.roles_create", params }); }
  subagentsRolesUpdate(params: protocol.SubagentRoleUpdateParams) { return this.send<protocol.SubagentRoleRecord>({ method: "subagents.roles_update", params }); }
  subagentsRolesDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "subagents.roles_delete", params }); }
  subagentsLaunch(params: protocol.SubagentLaunchParams) { return this.send<protocol.SubagentRunRecord>({ method: "subagents.launch", params }); }
  subagentsLaunchBatch(params: protocol.SubagentLaunchBatchParams) { return this.send<protocol.SubagentRunRecord[]>({ method: "subagents.launch_batch", params }); }
  subagentsRunsList(params: protocol.SubagentRunListParams) { return this.send<protocol.SubagentRunRecord[]>({ method: "subagents.runs_list", params }); }
  subagentsRunsGet(params: protocol.LegacyIdParams) { return this.send<protocol.SubagentRunDetailRecord>({ method: "subagents.runs_get", params }); }
  subagentsRunsCancel(params: protocol.IdempotentIdParams) { return this.send<protocol.SubagentRunCancelResult>({ method: "subagents.runs_cancel", params }); }
  subagentsRunsDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.LegacyOkResult>({ method: "subagents.runs_delete", params }); }
  inspectorTimeline(params: protocol.LegacyIdParams) { return this.send<protocol.TimelineRecord>({ method: "inspector.timeline", params }); }
  inspectorCompare(params: protocol.InspectorCompareParams) { return this.send<protocol.RunComparisonRecord>({ method: "inspector.compare", params }); }
  inspectorReplay(params: protocol.ReplayParams) { return this.send<protocol.ReplayResult>({ method: "inspector.replay", params }); }
  budgetsGet(params: protocol.EmptyParams) { return this.send<protocol.BudgetStatusRecord>({ method: "budgets.get", params }); }
  budgetsUpdate(params: protocol.BudgetUpdateParams) { return this.send<protocol.BudgetStatusRecord>({ method: "budgets.update", params }); }
  budgetsOverrideSet(params: protocol.BudgetOverrideParams) { return this.send<protocol.BudgetStatusRecord>({ method: "budgets.override_set", params }); }
  budgetsOverrideClear(params: protocol.IdempotentParams) { return this.send<protocol.BudgetStatusRecord>({ method: "budgets.override_clear", params }); }
  budgetsSpend(params: protocol.BudgetSpendParams) { return this.send<protocol.SpendEntryRecord[]>({ method: "budgets.spend", params }); }
  artifactsList(params: protocol.ArtifactListParams) { return this.send<protocol.ArtifactRecord[]>({ method: "artifacts.list", params }); }
  artifactsGet(params: protocol.ArtifactIdParams) { return this.send<protocol.ArtifactDetailRecord>({ method: "artifacts.get", params }); }
  artifactsDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "artifacts.delete", params }); }
  workspaceGitInfo(params: protocol.WorkspacePathParams) { return this.send<protocol.GitInfoRecord>({ method: "workspace.git_info", params }); }
  workspaceDirectories(params: protocol.WorkspaceOptionalPathParams) { return this.send<protocol.DirectoryListingRecord>({ method: "workspace.directories", params }); }
  workspaceRecent(params: protocol.EmptyParams) { return this.send<protocol.RecentDirectoriesRecord>({ method: "workspace.recent", params }); }
  workspaceGitStatus(params: protocol.WorkspacePathParams) { return this.send<protocol.GitStatusRecord>({ method: "workspace.git_status", params }); }
  workspaceGitLog(params: protocol.WorkspaceGitLogParams) { return this.send<protocol.GitLogRecord>({ method: "workspace.git_log", params }); }
  workspaceGitBranches(params: protocol.WorkspacePathParams) { return this.send<protocol.GitBranchesRecord>({ method: "workspace.git_branches", params }); }
  workspaceGitCheckout(params: protocol.WorkspaceGitCheckoutParams) { return this.send<protocol.GitCheckoutResult>({ method: "workspace.git_checkout", params }); }
  profilesList(params: protocol.ProfileListParams) { return this.send<protocol.ProfileRecord[]>({ method: "profiles.list", params }); }
  profilesGet(params: protocol.LegacyIdParams) { return this.send<protocol.ProfileRecord>({ method: "profiles.get", params }); }
  profilesCreate(params: protocol.ProfileCreateParams) { return this.send<protocol.ProfileRecord>({ method: "profiles.create", params }); }
  profilesUpdate(params: protocol.ProfileUpdateParams) { return this.send<protocol.ProfileRecord>({ method: "profiles.update", params }); }
  profilesDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "profiles.delete", params }); }
  profilesSeed(params: protocol.IdempotentParams) { return this.send<protocol.SeedResult>({ method: "profiles.seed", params }); }
  profilesClone(params: protocol.IdempotentIdParams) { return this.send<protocol.ProfileRecord>({ method: "profiles.clone", params }); }
  profilesPlayground(params: protocol.ProfilePlaygroundParams) { return this.send<protocol.PlaygroundResult>({ method: "profiles.playground", params }); }
  analyticsSummary(params: protocol.AnalyticsDaysParams) { return this.send<protocol.AnalyticsSummaryRecord>({ method: "analytics.summary", params }); }
  analyticsSpendOverTime(params: protocol.AnalyticsBucketParams) { return this.send<protocol.SpendBucketRecord[]>({ method: "analytics.spend_over_time", params }); }
  analyticsSpendByModel(params: protocol.AnalyticsDaysParams) { return this.send<protocol.ModelSpendRecord[]>({ method: "analytics.spend_by_model", params }); }
  analyticsTopTools(params: protocol.AnalyticsTopToolsParams) { return this.send<protocol.ToolUsageRecord[]>({ method: "analytics.top_tools", params }); }
  analyticsLatency(params: protocol.AnalyticsBucketParams) { return this.send<protocol.LatencyBucketRecord[]>({ method: "analytics.latency", params }); }
  analyticsCallHistory(params: protocol.AnalyticsCallHistoryParams) { return this.send<protocol.CallHistoryResult>({ method: "analytics.call_history", params }); }
  analyticsMemoryActivity(params: protocol.AnalyticsBucketParams) { return this.send<protocol.MemoryActivityBucketRecord[]>({ method: "analytics.memory_activity", params }); }
  tasksList(params: protocol.TaskListParams) { return this.send<protocol.TaskRecord[]>({ method: "tasks.list", params }); }
  tasksGet(params: protocol.LegacyIdParams) { return this.send<protocol.TaskRecord>({ method: "tasks.get", params }); }
  tasksCreate(params: protocol.TaskCreateParams) { return this.send<protocol.TaskRecord>({ method: "tasks.create", params }); }
  tasksUpdate(params: protocol.TaskUpdateParams) { return this.send<protocol.TaskRecord>({ method: "tasks.update", params }); }
  tasksDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "tasks.delete", params }); }
  tasksRun(params: protocol.IdempotentIdParams) { return this.send<protocol.TaskRunRecord>({ method: "tasks.run", params }); }
  tasksRunsList(params: protocol.TaskRunsParams) { return this.send<protocol.TaskRunRecord[]>({ method: "tasks.runs_list", params }); }
  tasksRunsGet(params: protocol.LegacyIdParams) { return this.send<protocol.TaskRunDetailRecord>({ method: "tasks.runs_get", params }); }
  tasksRunsCancel(params: protocol.IdempotentIdParams) { return this.send<protocol.TaskRunCancelResult>({ method: "tasks.runs_cancel", params }); }
  tasksRunsRead(params: protocol.TaskRunReadParams) { return this.send<protocol.TaskRunRecord>({ method: "tasks.runs_read", params }); }
  tasksInbox(params: protocol.TaskInboxParams) { return this.send<protocol.TaskInboxResult>({ method: "tasks.inbox", params }); }
  tasksScheduler(params: protocol.EmptyParams) { return this.send<protocol.SchedulerStatusRecord>({ method: "tasks.scheduler", params }); }
  tasksParseCron(params: protocol.ParseCronParams) { return this.send<protocol.ParseCronResult>({ method: "tasks.parse_cron", params }); }
  rssSubscriptionsList(params: protocol.RssSubscriptionListParams) { return this.send<protocol.RssSubscriptionRecord[]>({ method: "rss.subscriptions_list", params }); }
  rssSubscribe(params: protocol.RssSubscribeParams) { return this.send<protocol.RssSubscriptionRecord>({ method: "rss.subscribe", params }); }
  rssUnsubscribe(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "rss.unsubscribe", params }); }
  rssEntriesList(params: protocol.RssEntriesParams) { return this.send<protocol.RssEntryRecord[]>({ method: "rss.entries_list", params }); }
  rssEntriesAll(params: protocol.RssAllEntriesParams) { return this.send<protocol.RssEntryRecord[]>({ method: "rss.entries_all", params }); }
  rssEntryRead(params: protocol.RssEntryReadParams) { return this.send<protocol.RssEntryRecord>({ method: "rss.entry_read", params }); }
  webhooksList(params: protocol.EmptyParams) { return this.send<protocol.WebhookEndpointRecord[]>({ method: "webhooks.list", params }); }
  webhooksGet(params: protocol.LegacyIdParams) { return this.send<protocol.WebhookEndpointRecord>({ method: "webhooks.get", params }); }
  webhooksCreate(params: protocol.WebhookCreateParams) { return this.send<protocol.WebhookEndpointRecord>({ method: "webhooks.create", params }); }
  webhooksUpdate(params: protocol.WebhookUpdateParams) { return this.send<protocol.WebhookEndpointRecord>({ method: "webhooks.update", params }); }
  webhooksDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "webhooks.delete", params }); }
  webhooksEvents(params: protocol.WebhookEventsParams) { return this.send<protocol.WebhookEventRecord[]>({ method: "webhooks.events", params }); }
  webhooksReplay(params: protocol.WebhookReplayParams) { return this.send<protocol.WebhookEventRecord>({ method: "webhooks.replay", params }); }
  wikiList(params: protocol.WikiListParams) { return this.send<protocol.WikiArticleRecord[]>({ method: "wiki.list", params }); }
  wikiSearch(params: protocol.WikiSearchParams) { return this.send<protocol.WikiArticleRecord[]>({ method: "wiki.search", params }); }
  wikiGet(params: protocol.LegacyIdParams) { return this.send<protocol.WikiArticleRecord>({ method: "wiki.get", params }); }
  wikiCreate(params: protocol.WikiCreateParams) { return this.send<protocol.WikiArticleRecord>({ method: "wiki.create", params }); }
  wikiUpdate(params: protocol.WikiUpdateParams) { return this.send<protocol.WikiArticleRecord>({ method: "wiki.update", params }); }
  wikiDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "wiki.delete", params }); }
  wikiCategories(params: protocol.EmptyParams) { return this.send<string[]>({ method: "wiki.categories", params }); }
  wikiStats(params: protocol.EmptyParams) { return this.send<protocol.WikiStatsRecord>({ method: "wiki.stats", params }); }
  wikiPromote(params: protocol.WikiPromoteParams) { return this.send<protocol.WikiArticleRecord>({ method: "wiki.promote", params }); }
  researchList(params: protocol.ResearchListParams) { return this.send<protocol.ResearchRunRecord[]>({ method: "research.list", params }); }
  researchGet(params: protocol.LegacyIdParams) { return this.send<protocol.ResearchRunDetailRecord>({ method: "research.get", params }); }
  researchCreate(params: protocol.ResearchCreateParams) { return this.send<protocol.ResearchRunRecord>({ method: "research.create", params }); }
  researchCancel(params: protocol.IdempotentIdParams) { return this.send<protocol.ResearchCancelResult>({ method: "research.cancel", params }); }
  researchRerun(params: protocol.ResearchRerunParams) { return this.send<protocol.ResearchRunRecord>({ method: "research.rerun", params }); }
  constructorMacros(params: protocol.ConstructorMacroListParams) { return this.send<protocol.MacroToolRecord[]>({ method: "constructor.macros", params }); }
  constructorMacrosCreate(params: protocol.MacroCreateParams) { return this.send<protocol.MacroToolRecord>({ method: "constructor.macros_create", params }); }
  constructorMacrosUpdate(params: protocol.MacroUpdateParams) { return this.send<protocol.MacroToolRecord>({ method: "constructor.macros_update", params }); }
  constructorMacrosDelete(params: protocol.IdempotentIdParams) { return this.send<protocol.DeletedResult>({ method: "constructor.macros_delete", params }); }
}
