"""Plan routes: CRUD, approval, execution, and templates (Фаза 2 §1).

Plans are generated by the agent when plan_mode is active (see conversations
router). These endpoints let the client review, edit, approve, and execute
plans, plus manage reusable plan templates.

  GET    /conversations/{conv}/plans                  — list plans
  GET    /conversations/{conv}/plans/{plan}           — plan detail with steps
  PATCH  /conversations/{conv}/plans/{plan}           — edit draft plan
  POST   /conversations/{conv}/plans/{plan}/approve   — approve a draft plan
  POST   /conversations/{conv}/plans/{plan}/cancel    — cancel a plan
  POST   /conversations/{conv}/plans/{plan}/execute   — SSE stream execution
  GET    /plan-templates                              — list templates
  POST   /plan-templates                              — create template
  DELETE /plan-templates/{id}                         — delete template
"""

from __future__ import annotations

from collections.abc import AsyncIterator

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session
from sse_starlette.sse import EventSourceResponse

from app.agent.planning import (
    approve_plan,
    cancel_plan,
    create_template,
    delete_template,
    execute_plan_steps,
    get_plan,
    get_plan_steps,
    list_plans,
    list_templates,
    update_plan_steps,
)
from app.agent.service import get_conversation, load_history
from app.api.schemas import (
    PlanApproveRequest,
    PlanOut,
    PlanStepOut,
    PlanTemplateCreate,
    PlanTemplateOut,
    PlanUpdate,
)
from app.core.db import get_session
from app.models.plan import PLAN_STATUS_APPROVED
from app.providers import get_provider_for_model

router = APIRouter()


def _require_conversation(session: Session, conv_id: int) -> None:
    if get_conversation(session, conv_id) is None:
        raise HTTPException(status_code=404, detail="Conversation not found")


def _require_plan(session: Session, conv_id: int, plan_id: int):
    _require_conversation(session, conv_id)
    plan = get_plan(session, plan_id)
    if plan is None or plan.conversation_id != conv_id:
        raise HTTPException(status_code=404, detail="Plan not found")
    return plan


def _plan_to_out(session: Session, plan) -> PlanOut:
    steps = get_plan_steps(session, plan.id)
    return PlanOut(
        id=plan.id,
        conversation_id=plan.conversation_id,
        run_id=plan.run_id,
        title=plan.title,
        status=plan.status,
        steps=[
            PlanStepOut(
                position=s.position,
                title=s.title,
                description=s.description,
                status=s.status,
                depends_on=s.depends_on,
                tools=s.tools,
                result_summary=s.result_summary,
            )
            for s in steps
        ],
        created_at=plan.created_at,
        updated_at=plan.updated_at,
    )


# --- Plan CRUD ---


@router.get("/conversations/{conv_id}/plans", response_model=list[PlanOut])
def list_conversation_plans(conv_id: int, session: Session = Depends(get_session)) -> list[PlanOut]:
    """List plans for a conversation, newest first."""
    _require_conversation(session, conv_id)
    plans = list_plans(session, conversation_id=conv_id)
    return [_plan_to_out(session, p) for p in plans]


@router.get("/conversations/{conv_id}/plans/{plan_id}", response_model=PlanOut)
def get_plan_detail(conv_id: int, plan_id: int, session: Session = Depends(get_session)) -> PlanOut:
    """Plan detail with steps."""
    plan = _require_plan(session, conv_id, plan_id)
    return _plan_to_out(session, plan)


@router.patch("/conversations/{conv_id}/plans/{plan_id}", response_model=PlanOut)
def patch_plan(
    conv_id: int, plan_id: int, body: PlanUpdate, session: Session = Depends(get_session)
) -> PlanOut:
    """Edit a draft plan's title and/or steps (before approval)."""
    _require_plan(session, conv_id, plan_id)
    steps_data = None
    if body.steps is not None:
        steps_data = [s.model_dump() for s in body.steps]
    plan = update_plan_steps(session, plan_id, title=body.title, steps=steps_data)
    if plan is None:
        raise HTTPException(status_code=400, detail="Plan not found or not in draft status")
    return _plan_to_out(session, plan)


@router.post("/conversations/{conv_id}/plans/{plan_id}/approve", response_model=PlanOut)
def post_plan_approve(
    conv_id: int, plan_id: int, body: PlanApproveRequest, session: Session = Depends(get_session)
) -> PlanOut:
    """Approve or reject a draft plan.

    If approved, the plan transitions to 'approved' and can be executed.
    If rejected (approved=False), the plan is cancelled.
    """
    _require_plan(session, conv_id, plan_id)
    if body.approved:
        plan = approve_plan(session, plan_id)
        if plan is None:
            raise HTTPException(status_code=400, detail="Plan not found or not in draft status")
    else:
        plan = cancel_plan(session, plan_id)
        if plan is None:
            raise HTTPException(status_code=400, detail="Plan not found or already terminal")
    return _plan_to_out(session, plan)


@router.post("/conversations/{conv_id}/plans/{plan_id}/cancel", response_model=PlanOut)
def post_plan_cancel(conv_id: int, plan_id: int, session: Session = Depends(get_session)) -> PlanOut:
    """Cancel a plan (from any non-terminal status)."""
    _require_plan(session, conv_id, plan_id)
    plan = cancel_plan(session, plan_id)
    if plan is None:
        raise HTTPException(status_code=400, detail="Plan not found or already terminal")
    return _plan_to_out(session, plan)


# --- Plan execution (SSE) ---


@router.post("/conversations/{conv_id}/plans/{plan_id}/execute")
async def post_plan_execute(
    conv_id: int, plan_id: int, session: Session = Depends(get_session)
) -> EventSourceResponse:
    """Execute an approved plan step-by-step, streaming progress as SSE events.

    The plan must be in 'approved' status. Each step runs as a focused agent
    sub-turn; progress events (plan_step_start, plan_step_complete, plan_progress)
    are streamed to the client.
    """
    conv = get_conversation(session, conv_id)
    if conv is None:
        raise HTTPException(status_code=404, detail="Conversation not found")
    plan = get_plan(session, plan_id)
    if plan is None or plan.conversation_id != conv_id:
        raise HTTPException(status_code=404, detail="Plan not found")
    if plan.status != PLAN_STATUS_APPROVED:
        raise HTTPException(status_code=400, detail="Plan must be approved before execution")

    model = conv.model
    if not model:
        raise HTTPException(status_code=400, detail="Conversation has no model configured")
    provider = get_provider_for_model(model)
    history = load_history(session, conv_id)

    async def event_stream() -> AsyncIterator[dict]:
        async for event in execute_plan_steps(
            session,
            plan,
            provider=provider,
            model=model,
            history=history,
            working_directory=conv.working_directory,
        ):
            yield {"event": event.kind, "data": event.to_dict_json()}

    return EventSourceResponse(event_stream())


# --- Plan templates ---


@router.get("/plan-templates", response_model=list[PlanTemplateOut])
def get_plan_templates(session: Session = Depends(get_session)) -> list[PlanTemplateOut]:
    """List all plan templates."""
    templates = list_templates(session)
    return [
        PlanTemplateOut(
            id=t.id,  # type: ignore[arg-type]
            name=t.name,
            description=t.description,
            steps=t.steps,
            is_builtin=t.is_builtin,
            created_at=t.created_at,
            updated_at=t.updated_at,
        )
        for t in templates
    ]


@router.post("/plan-templates", response_model=PlanTemplateOut)
def post_plan_template(
    body: PlanTemplateCreate, session: Session = Depends(get_session)
) -> PlanTemplateOut:
    """Create a new plan template."""
    tpl = create_template(session, name=body.name, description=body.description, steps=body.steps)
    return PlanTemplateOut(
        id=tpl.id,  # type: ignore[arg-type]
        name=tpl.name,
        description=tpl.description,
        steps=tpl.steps,
        is_builtin=tpl.is_builtin,
        created_at=tpl.created_at,
        updated_at=tpl.updated_at,
    )


@router.delete("/plan-templates/{template_id}")
def delete_plan_template(template_id: int, session: Session = Depends(get_session)) -> dict:
    """Delete a plan template (built-in templates cannot be deleted)."""
    if not delete_template(session, template_id):
        raise HTTPException(status_code=404, detail="Template not found or is built-in")
    return {"deleted": template_id}
