[package]
name = "cool-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
cool-security = { path = "../cool-security", version = "0.2.1" }
cool-state = { path = "../cool-state", version = "0.2.1" }
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
